region                        = "eu-west-2"
environment_name              = "dev"
remote_backend_name           = "aws-nuke-tf-state"
aws_nuke_resource_name_prefix = "aws-nuke-access-delegator"
owner                         = "Abhishek Rajput"
description                   = "resources for aws-nuke in repo https://github.com/abhisheksr01/cloud-infrastructure-nuke"