name: nuke-gcp-projects

on:
  schedule:
    - cron:  '0 17 * * 5'
  workflow_dispatch:

jobs:
  nuke-gcp-projects:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - run: make gcp-nuke-projects